remote_theme: daattali/beautiful-jekyll

# Name of website
title: Matematica Discreta

# Your name to show in the footer
author: Carlos Florentino

# Navegador
navbar-links:
  Programa: "programa"
  Recursos:
    - Beautiful Jekyll: "https://beautifuljekyll.com"
    - Learn markdown: "https://www.markdowntutorial.com/"
  Avaliação: "https://deanattali.com"
