remote_theme: daattali/beautiful-jekyll

# Name of website
title: Fundação Daniel da Silva

# Your name to show in the footer
author: C. Florentino

# Navegador
navbar-links:
  Daniel da Silva:
    - História: "horarios"
    - Matemática: "exercicios"
    - Ciência: "programa"
  Actividades:
    - Eventos: "https://www.youtube.com/c/Matem%C3%A1ticaDiscretaFCUL"
    - Prémios: "ligacoes"
  Recursos:
    - Obras Completas: "avaliacao"
    - Outras Ligações: "testes"

markdown: kramdown

# --- Colours / background image --- #

# Personalize the colours in your website. Colour values can be any valid CSS colour

navbar-col: "#14121C"
navbar-text-col: "#C0C0C0"
navbar-border-col: "#FFAC6C"
page-col: "#505F6B"
text-col: "#FFFFFF"
link-col: "#008AFF"
hover-col: "#0085A1"
footer-col: "#14121C"
footer-text-col: "#C0C0C0"
footer-link-col: "#404040"
footer-hover-col: "#0085A1"
