remote_theme: daattali/beautiful-jekyll

# Name of website
title: Matemática Discreta / Finita - FCUL '22

# Your name to show in the footer
author: Carlos Florentino

# Navegador
navbar-links:
  Programa: "programa"
  Horário: "horarios"
  Recursos:
    - Apontamentos: "teoricas"
    - Vídeos: "https://www.youtube.com/c/Matem%C3%A1ticaDiscretaFCUL"
    - Exercícios: "exercicios"
  Avaliação: "avaliacao"
